// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package urldb

type Url struct {
	Key      string `json:"key"`
	Longurl  string `json:"longurl"`
	Shorturl string `json:"shorturl"`
}
